import UniDeskCppExt.udcpptools

class Calculator:
    def __init__(self) -> None: ...
    def add(self, value: int) -> None: ...
    def subtract(self, value: int) -> None: ...
    def get_result(self) -> int: ...