from typing import Any, Optional

from dev.coatl.helper.types import AnyStr

def fileExists(filepath: AnyStr) -> bool: ...
def getTempFile(extension: AnyStr) -> AnyStr: ...
def readFileAsBytes(filepath: AnyStr) -> Any: ...
def readFileAsString(filepath: AnyStr, encoding: Optional[AnyStr] = ...) -> AnyStr: ...
def writeFile(
    filepath: AnyStr, data: Any, append: bool = ..., encoding: AnyStr = ...
) -> None: ...
