# coding: utf-8

"""
    Plans (Beta)

 

    OpenAPI spec version: v2024.20.0
     
"""

import pprint
import re  # noqa: F401

import six

class RunParameterResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'plan_node_parameters': 'list[RunParameterResponsePlanNodeParameters]'
    }

    attribute_map = {
        'plan_node_parameters': 'planNodeParameters'
    }

    def __init__(self, plan_node_parameters=None):  # noqa: E501
        """RunParameterResponse - a model defined in Swagger"""  # noqa: E501
        self._plan_node_parameters = None
        self.discriminator = None
        self.plan_node_parameters = plan_node_parameters

    @property
    def plan_node_parameters(self):
        """Gets the plan_node_parameters of this RunParameterResponse.  # noqa: E501


        :return: The plan_node_parameters of this RunParameterResponse.  # noqa: E501
        :rtype: list[RunParameterResponsePlanNodeParameters]
        """
        return self._plan_node_parameters

    @plan_node_parameters.setter
    def plan_node_parameters(self, plan_node_parameters):
        """Sets the plan_node_parameters of this RunParameterResponse.


        :param plan_node_parameters: The plan_node_parameters of this RunParameterResponse.  # noqa: E501
        :type: list[RunParameterResponsePlanNodeParameters]
        """
        if plan_node_parameters is None:
            raise ValueError("Invalid value for `plan_node_parameters`, must not be `None`")  # noqa: E501

        self._plan_node_parameters = plan_node_parameters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RunParameterResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RunParameterResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
