from .._base import imgui as imgui
from .._scopes_storage import scopes_parents as scopes_parents

def child_id() -> int: ...
def get_scope_parent() -> object | None: ...
def set_scope_parent(parent: object): ...
def clear_scopes_parents() -> None: ...
