# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vessl.openapi_client.configuration import Configuration


class OrmProjectDashboard(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'created_by_id': 'int',
        'created_dt': 'datetime',
        'edges': 'OrmProjectDashboardEdges',
        'id': 'int',
        'is_main': 'bool',
        'is_private': 'bool',
        'last_updated_by_id': 'int',
        'last_updated_dt': 'datetime',
        'name': 'str',
        'project_id': 'int',
        'updated_dt': 'datetime'
    }

    attribute_map = {
        'created_by_id': 'created_by_id',
        'created_dt': 'created_dt',
        'edges': 'edges',
        'id': 'id',
        'is_main': 'is_main',
        'is_private': 'is_private',
        'last_updated_by_id': 'last_updated_by_id',
        'last_updated_dt': 'last_updated_dt',
        'name': 'name',
        'project_id': 'project_id',
        'updated_dt': 'updated_dt'
    }

    def __init__(self, created_by_id=None, created_dt=None, edges=None, id=None, is_main=None, is_private=None, last_updated_by_id=None, last_updated_dt=None, name=None, project_id=None, updated_dt=None, local_vars_configuration=None):  # noqa: E501
        """OrmProjectDashboard - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._created_by_id = None
        self._created_dt = None
        self._edges = None
        self._id = None
        self._is_main = None
        self._is_private = None
        self._last_updated_by_id = None
        self._last_updated_dt = None
        self._name = None
        self._project_id = None
        self._updated_dt = None
        self.discriminator = None

        self.created_by_id = created_by_id
        if created_dt is not None:
            self.created_dt = created_dt
        if edges is not None:
            self.edges = edges
        if id is not None:
            self.id = id
        if is_main is not None:
            self.is_main = is_main
        if is_private is not None:
            self.is_private = is_private
        self.last_updated_by_id = last_updated_by_id
        self.last_updated_dt = last_updated_dt
        if name is not None:
            self.name = name
        if project_id is not None:
            self.project_id = project_id
        if updated_dt is not None:
            self.updated_dt = updated_dt

    @property
    def created_by_id(self):
        """Gets the created_by_id of this OrmProjectDashboard.  # noqa: E501


        :return: The created_by_id of this OrmProjectDashboard.  # noqa: E501
        :rtype: int
        """
        return self._created_by_id

    @created_by_id.setter
    def created_by_id(self, created_by_id):
        """Sets the created_by_id of this OrmProjectDashboard.


        :param created_by_id: The created_by_id of this OrmProjectDashboard.  # noqa: E501
        :type created_by_id: int
        """

        self._created_by_id = created_by_id

    @property
    def created_dt(self):
        """Gets the created_dt of this OrmProjectDashboard.  # noqa: E501


        :return: The created_dt of this OrmProjectDashboard.  # noqa: E501
        :rtype: datetime
        """
        return self._created_dt

    @created_dt.setter
    def created_dt(self, created_dt):
        """Sets the created_dt of this OrmProjectDashboard.


        :param created_dt: The created_dt of this OrmProjectDashboard.  # noqa: E501
        :type created_dt: datetime
        """

        self._created_dt = created_dt

    @property
    def edges(self):
        """Gets the edges of this OrmProjectDashboard.  # noqa: E501


        :return: The edges of this OrmProjectDashboard.  # noqa: E501
        :rtype: OrmProjectDashboardEdges
        """
        return self._edges

    @edges.setter
    def edges(self, edges):
        """Sets the edges of this OrmProjectDashboard.


        :param edges: The edges of this OrmProjectDashboard.  # noqa: E501
        :type edges: OrmProjectDashboardEdges
        """

        self._edges = edges

    @property
    def id(self):
        """Gets the id of this OrmProjectDashboard.  # noqa: E501


        :return: The id of this OrmProjectDashboard.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OrmProjectDashboard.


        :param id: The id of this OrmProjectDashboard.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def is_main(self):
        """Gets the is_main of this OrmProjectDashboard.  # noqa: E501


        :return: The is_main of this OrmProjectDashboard.  # noqa: E501
        :rtype: bool
        """
        return self._is_main

    @is_main.setter
    def is_main(self, is_main):
        """Sets the is_main of this OrmProjectDashboard.


        :param is_main: The is_main of this OrmProjectDashboard.  # noqa: E501
        :type is_main: bool
        """

        self._is_main = is_main

    @property
    def is_private(self):
        """Gets the is_private of this OrmProjectDashboard.  # noqa: E501


        :return: The is_private of this OrmProjectDashboard.  # noqa: E501
        :rtype: bool
        """
        return self._is_private

    @is_private.setter
    def is_private(self, is_private):
        """Sets the is_private of this OrmProjectDashboard.


        :param is_private: The is_private of this OrmProjectDashboard.  # noqa: E501
        :type is_private: bool
        """

        self._is_private = is_private

    @property
    def last_updated_by_id(self):
        """Gets the last_updated_by_id of this OrmProjectDashboard.  # noqa: E501


        :return: The last_updated_by_id of this OrmProjectDashboard.  # noqa: E501
        :rtype: int
        """
        return self._last_updated_by_id

    @last_updated_by_id.setter
    def last_updated_by_id(self, last_updated_by_id):
        """Sets the last_updated_by_id of this OrmProjectDashboard.


        :param last_updated_by_id: The last_updated_by_id of this OrmProjectDashboard.  # noqa: E501
        :type last_updated_by_id: int
        """

        self._last_updated_by_id = last_updated_by_id

    @property
    def last_updated_dt(self):
        """Gets the last_updated_dt of this OrmProjectDashboard.  # noqa: E501


        :return: The last_updated_dt of this OrmProjectDashboard.  # noqa: E501
        :rtype: datetime
        """
        return self._last_updated_dt

    @last_updated_dt.setter
    def last_updated_dt(self, last_updated_dt):
        """Sets the last_updated_dt of this OrmProjectDashboard.


        :param last_updated_dt: The last_updated_dt of this OrmProjectDashboard.  # noqa: E501
        :type last_updated_dt: datetime
        """

        self._last_updated_dt = last_updated_dt

    @property
    def name(self):
        """Gets the name of this OrmProjectDashboard.  # noqa: E501


        :return: The name of this OrmProjectDashboard.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OrmProjectDashboard.


        :param name: The name of this OrmProjectDashboard.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def project_id(self):
        """Gets the project_id of this OrmProjectDashboard.  # noqa: E501


        :return: The project_id of this OrmProjectDashboard.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this OrmProjectDashboard.


        :param project_id: The project_id of this OrmProjectDashboard.  # noqa: E501
        :type project_id: int
        """

        self._project_id = project_id

    @property
    def updated_dt(self):
        """Gets the updated_dt of this OrmProjectDashboard.  # noqa: E501


        :return: The updated_dt of this OrmProjectDashboard.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_dt

    @updated_dt.setter
    def updated_dt(self, updated_dt):
        """Sets the updated_dt of this OrmProjectDashboard.


        :param updated_dt: The updated_dt of this OrmProjectDashboard.  # noqa: E501
        :type updated_dt: datetime
        """

        self._updated_dt = updated_dt

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrmProjectDashboard):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrmProjectDashboard):
            return True

        return self.to_dict() != other.to_dict()
