# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vessl.openapi_client.configuration import Configuration


class OrmAccessControlConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'artifact': 'str',
        'credentials': 'str',
        'project': 'str',
        'workspace': 'str'
    }

    attribute_map = {
        'artifact': 'artifact',
        'credentials': 'credentials',
        'project': 'project',
        'workspace': 'workspace'
    }

    def __init__(self, artifact=None, credentials=None, project=None, workspace=None, local_vars_configuration=None):  # noqa: E501
        """OrmAccessControlConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._artifact = None
        self._credentials = None
        self._project = None
        self._workspace = None
        self.discriminator = None

        if artifact is not None:
            self.artifact = artifact
        if credentials is not None:
            self.credentials = credentials
        if project is not None:
            self.project = project
        if workspace is not None:
            self.workspace = workspace

    @property
    def artifact(self):
        """Gets the artifact of this OrmAccessControlConfig.  # noqa: E501


        :return: The artifact of this OrmAccessControlConfig.  # noqa: E501
        :rtype: str
        """
        return self._artifact

    @artifact.setter
    def artifact(self, artifact):
        """Sets the artifact of this OrmAccessControlConfig.


        :param artifact: The artifact of this OrmAccessControlConfig.  # noqa: E501
        :type artifact: str
        """

        self._artifact = artifact

    @property
    def credentials(self):
        """Gets the credentials of this OrmAccessControlConfig.  # noqa: E501


        :return: The credentials of this OrmAccessControlConfig.  # noqa: E501
        :rtype: str
        """
        return self._credentials

    @credentials.setter
    def credentials(self, credentials):
        """Sets the credentials of this OrmAccessControlConfig.


        :param credentials: The credentials of this OrmAccessControlConfig.  # noqa: E501
        :type credentials: str
        """

        self._credentials = credentials

    @property
    def project(self):
        """Gets the project of this OrmAccessControlConfig.  # noqa: E501


        :return: The project of this OrmAccessControlConfig.  # noqa: E501
        :rtype: str
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this OrmAccessControlConfig.


        :param project: The project of this OrmAccessControlConfig.  # noqa: E501
        :type project: str
        """

        self._project = project

    @property
    def workspace(self):
        """Gets the workspace of this OrmAccessControlConfig.  # noqa: E501


        :return: The workspace of this OrmAccessControlConfig.  # noqa: E501
        :rtype: str
        """
        return self._workspace

    @workspace.setter
    def workspace(self, workspace):
        """Sets the workspace of this OrmAccessControlConfig.


        :param workspace: The workspace of this OrmAccessControlConfig.  # noqa: E501
        :type workspace: str
        """

        self._workspace = workspace

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrmAccessControlConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrmAccessControlConfig):
            return True

        return self.to_dict() != other.to_dict()
