# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vessl.openapi_client.configuration import Configuration


class ProtoResourcePreset(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cluster_id': 'int',
        'description': 'str',
        'id': 'int',
        'name': 'str',
        'spec': 'V1KernelResourceSpec'
    }

    attribute_map = {
        'cluster_id': 'cluster_id',
        'description': 'description',
        'id': 'id',
        'name': 'name',
        'spec': 'spec'
    }

    def __init__(self, cluster_id=None, description=None, id=None, name=None, spec=None, local_vars_configuration=None):  # noqa: E501
        """ProtoResourcePreset - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._cluster_id = None
        self._description = None
        self._id = None
        self._name = None
        self._spec = None
        self.discriminator = None

        if cluster_id is not None:
            self.cluster_id = cluster_id
        self.description = description
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if spec is not None:
            self.spec = spec

    @property
    def cluster_id(self):
        """Gets the cluster_id of this ProtoResourcePreset.  # noqa: E501


        :return: The cluster_id of this ProtoResourcePreset.  # noqa: E501
        :rtype: int
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """Sets the cluster_id of this ProtoResourcePreset.


        :param cluster_id: The cluster_id of this ProtoResourcePreset.  # noqa: E501
        :type cluster_id: int
        """

        self._cluster_id = cluster_id

    @property
    def description(self):
        """Gets the description of this ProtoResourcePreset.  # noqa: E501


        :return: The description of this ProtoResourcePreset.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ProtoResourcePreset.


        :param description: The description of this ProtoResourcePreset.  # noqa: E501
        :type description: str
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this ProtoResourcePreset.  # noqa: E501


        :return: The id of this ProtoResourcePreset.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProtoResourcePreset.


        :param id: The id of this ProtoResourcePreset.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ProtoResourcePreset.  # noqa: E501


        :return: The name of this ProtoResourcePreset.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProtoResourcePreset.


        :param name: The name of this ProtoResourcePreset.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def spec(self):
        """Gets the spec of this ProtoResourcePreset.  # noqa: E501


        :return: The spec of this ProtoResourcePreset.  # noqa: E501
        :rtype: V1KernelResourceSpec
        """
        return self._spec

    @spec.setter
    def spec(self, spec):
        """Sets the spec of this ProtoResourcePreset.


        :param spec: The spec of this ProtoResourcePreset.  # noqa: E501
        :type spec: V1KernelResourceSpec
        """

        self._spec = spec

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProtoResourcePreset):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProtoResourcePreset):
            return True

        return self.to_dict() != other.to_dict()
