# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vessl.openapi_client.configuration import Configuration


class ResponseUserGroupWithMetadata(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'description': 'str',
        'id': 'int',
        'is_member': 'bool',
        'member_count': 'int',
        'name': 'str',
        'special_type': 'str'
    }

    attribute_map = {
        'description': 'description',
        'id': 'id',
        'is_member': 'is_member',
        'member_count': 'member_count',
        'name': 'name',
        'special_type': 'special_type'
    }

    def __init__(self, description=None, id=None, is_member=None, member_count=None, name=None, special_type=None, local_vars_configuration=None):  # noqa: E501
        """ResponseUserGroupWithMetadata - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._description = None
        self._id = None
        self._is_member = None
        self._member_count = None
        self._name = None
        self._special_type = None
        self.discriminator = None

        self.description = description
        self.id = id
        self.is_member = is_member
        self.member_count = member_count
        self.name = name
        self.special_type = special_type

    @property
    def description(self):
        """Gets the description of this ResponseUserGroupWithMetadata.  # noqa: E501


        :return: The description of this ResponseUserGroupWithMetadata.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ResponseUserGroupWithMetadata.


        :param description: The description of this ResponseUserGroupWithMetadata.  # noqa: E501
        :type description: str
        """
        if self.local_vars_configuration.client_side_validation and description is None:  # noqa: E501
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def id(self):
        """Gets the id of this ResponseUserGroupWithMetadata.  # noqa: E501


        :return: The id of this ResponseUserGroupWithMetadata.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ResponseUserGroupWithMetadata.


        :param id: The id of this ResponseUserGroupWithMetadata.  # noqa: E501
        :type id: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def is_member(self):
        """Gets the is_member of this ResponseUserGroupWithMetadata.  # noqa: E501


        :return: The is_member of this ResponseUserGroupWithMetadata.  # noqa: E501
        :rtype: bool
        """
        return self._is_member

    @is_member.setter
    def is_member(self, is_member):
        """Sets the is_member of this ResponseUserGroupWithMetadata.


        :param is_member: The is_member of this ResponseUserGroupWithMetadata.  # noqa: E501
        :type is_member: bool
        """

        self._is_member = is_member

    @property
    def member_count(self):
        """Gets the member_count of this ResponseUserGroupWithMetadata.  # noqa: E501


        :return: The member_count of this ResponseUserGroupWithMetadata.  # noqa: E501
        :rtype: int
        """
        return self._member_count

    @member_count.setter
    def member_count(self, member_count):
        """Sets the member_count of this ResponseUserGroupWithMetadata.


        :param member_count: The member_count of this ResponseUserGroupWithMetadata.  # noqa: E501
        :type member_count: int
        """
        if self.local_vars_configuration.client_side_validation and member_count is None:  # noqa: E501
            raise ValueError("Invalid value for `member_count`, must not be `None`")  # noqa: E501

        self._member_count = member_count

    @property
    def name(self):
        """Gets the name of this ResponseUserGroupWithMetadata.  # noqa: E501


        :return: The name of this ResponseUserGroupWithMetadata.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ResponseUserGroupWithMetadata.


        :param name: The name of this ResponseUserGroupWithMetadata.  # noqa: E501
        :type name: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def special_type(self):
        """Gets the special_type of this ResponseUserGroupWithMetadata.  # noqa: E501


        :return: The special_type of this ResponseUserGroupWithMetadata.  # noqa: E501
        :rtype: str
        """
        return self._special_type

    @special_type.setter
    def special_type(self, special_type):
        """Sets the special_type of this ResponseUserGroupWithMetadata.


        :param special_type: The special_type of this ResponseUserGroupWithMetadata.  # noqa: E501
        :type special_type: str
        """

        self._special_type = special_type

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseUserGroupWithMetadata):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ResponseUserGroupWithMetadata):
            return True

        return self.to_dict() != other.to_dict()
