# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vessl.openapi_client.configuration import Configuration


class ResponseNodePortConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'nodeport_ranges': 'list[str]',
        'service_annotations': 'dict[str, str]'
    }

    attribute_map = {
        'nodeport_ranges': 'nodeport_ranges',
        'service_annotations': 'service_annotations'
    }

    def __init__(self, nodeport_ranges=None, service_annotations=None, local_vars_configuration=None):  # noqa: E501
        """ResponseNodePortConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._nodeport_ranges = None
        self._service_annotations = None
        self.discriminator = None

        if nodeport_ranges is not None:
            self.nodeport_ranges = nodeport_ranges
        if service_annotations is not None:
            self.service_annotations = service_annotations

    @property
    def nodeport_ranges(self):
        """Gets the nodeport_ranges of this ResponseNodePortConfig.  # noqa: E501


        :return: The nodeport_ranges of this ResponseNodePortConfig.  # noqa: E501
        :rtype: list[str]
        """
        return self._nodeport_ranges

    @nodeport_ranges.setter
    def nodeport_ranges(self, nodeport_ranges):
        """Sets the nodeport_ranges of this ResponseNodePortConfig.


        :param nodeport_ranges: The nodeport_ranges of this ResponseNodePortConfig.  # noqa: E501
        :type nodeport_ranges: list[str]
        """

        self._nodeport_ranges = nodeport_ranges

    @property
    def service_annotations(self):
        """Gets the service_annotations of this ResponseNodePortConfig.  # noqa: E501


        :return: The service_annotations of this ResponseNodePortConfig.  # noqa: E501
        :rtype: dict[str, str]
        """
        return self._service_annotations

    @service_annotations.setter
    def service_annotations(self, service_annotations):
        """Sets the service_annotations of this ResponseNodePortConfig.


        :param service_annotations: The service_annotations of this ResponseNodePortConfig.  # noqa: E501
        :type service_annotations: dict[str, str]
        """

        self._service_annotations = service_annotations

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseNodePortConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ResponseNodePortConfig):
            return True

        return self.to_dict() != other.to_dict()
