from rich.box import HORIZONTALS, SQUARE

CLI_WIDTH = 100
CLI_BORDER_STYLE = "cyan"
CLI_HEADER_STYLE = "bold cyan"
CLI_PANEL_BOX_STYLE = SQUARE
CLI_TABLE_BOX_STYLE = SQUARE

MESSAGE_BOX_STYLE = SQUARE
TOOL_BOX_STYLE = SQUARE
LOADING_BOX_STYLE = HORIZONTALS

SPINNER_STYLES = [
    "balloon",
    "arc",
    "star",
    "star2",
    "line",
    "toggle13",
    "toggle10",
    "dots3",
    "boxBounce",
]

THINKING_WORDS = [
    "Pondering",
    "Contemplating",
    "Musing",
    "Analyzing",
    "Examining",
    "Processing",
    "Brainstorming",
    "Cogitating",
    "Divining",
    "Puzzling out",
    "Ideating",
    "Formulating",
    "Ruminating",
    "Vibe thonking",
    "Deliberating",
    "Orchestrating",
    "Synthesizing",
    "Computing",
    "Speculating",
    "Envisioning",
    "Exploring",
    "Deciphering",
    "Deducing",
    "Inferring",
    "Projecting",
    "Conceiving",
    "Reckoning",
    "Mapping out",
    "Strategizing",
    "Distilling",
    "Untangling",
    "Reflecting",
    "Diagnosing",
    "Measuring",
    "Balancing",
    "Probing",
    "Testing ideas",
    "Hypothesizing",
    "Abstracting",
    "Curating",
    "Reframing",
    "Modeling",
    "Architecting",
    "Comparing",
    "Contrasting",
    "Sequencing",
    "Predicting",
    "Imagining",
    "Rehearsing",
    "Crunching",
    "Debugging",
    "Optimizing",
    "Calibrating",
    "Harmonizing",
    "Systematizing",
    "Configuring",
    "Drafting",
    "Refining",
    "Parsing",
    "Interpreting",
    "Tuning",
    "Charting",
    "Layering thoughts",
    "Encoding",
    "Decoding",
    "Querying self",
    "Simulating",
    "Scanning",
    "Indexing",
    "Aligning",
    "Cross-checking",
    "Visualizing",
    "Reconstructing",
    "Evaluating",
    "Filtering",
    "Factoring in",
    "Plotting",
    "Diagramming",
    "Designing",
    "Correlating",
    "Associating",
    "Linking concepts",
    "Reassembling",
    "Aggregating",
    "Orchestrating thoughts",
    "Navigating",
    "Testing hypotheses",
    "Revising",
    "Iterating",
    "Connecting dots",
    "Reverse-engineering",
    "Pruning options",
]
