from .models import EntityLinkingConfig, MatchCondition, MatchType, FieldCondition, OrCondition, AndCondition


# Create a custom config with dictionary matching
default_config = EntityLinkingConfig(
    quick_creation_config=OrCondition(
        conditions=[
            FieldCondition(
                field="canonical_name",
                condition=MatchCondition(
                    match_type=MatchType.LEXICAL_SIMILARITY,
                    threshold=30
                )
            ),
            FieldCondition(
                field="canonical_name",
                condition=MatchCondition(
                    match_type=MatchType.SEMANTIC_SIMILARITY,
                    threshold=30
                )
            ),
            FieldCondition(
                field="aliases",
                condition=MatchCondition(
                    match_type=MatchType.LEXICAL_SIMILARITY_LIST,
                    threshold=30
                )
            ),
            FieldCondition(
                field="metadata",
                condition=MatchCondition(
                    match_type=MatchType.DICT_MATCH,
                    threshold=10,
                ),
                dict_mappings=[]
            )
        ]
    ),
    quick_linking_config=AndCondition(
        conditions=[
            FieldCondition(
                field="canonical_name",
                condition=MatchCondition(
                    match_type=MatchType.LEXICAL_SIMILARITY,
                    threshold=70
                )
            ),
            FieldCondition(
                field="canonical_name",
                condition=MatchCondition(
                    match_type=MatchType.SEMANTIC_SIMILARITY,
                    threshold=70
                )
            ),
            FieldCondition(
                field="aliases",
                condition=MatchCondition(
                    match_type=MatchType.LEXICAL_SIMILARITY_LIST,
                    threshold=80
                )
            ),
            FieldCondition(
                field="metadata",
                condition=MatchCondition(
                    match_type=MatchType.DICT_MATCH,
                    threshold=20,
                    weight=0.6
                ),
                dict_mappings=[]
            ),
        ]
    ),
    llm_linking_config=OrCondition(
        conditions=[
            FieldCondition(
                field="canonical_name",
                condition=MatchCondition(
                    match_type=MatchType.LEXICAL_SIMILARITY,
                    threshold=0,
                    weight=1.0
                )
            ),
            FieldCondition(
                field="canonical_name",
                condition=MatchCondition(
                    match_type=MatchType.SEMANTIC_SIMILARITY,
                    threshold=0,
                    weight=0.8
                )
            ),
            FieldCondition(
                field="aliases",
                condition=MatchCondition(
                    match_type=MatchType.LEXICAL_SIMILARITY_LIST,
                    threshold=0,
                    weight=0.6
                )
            ),
            FieldCondition(
                field="metadata",
                condition=MatchCondition(
                    match_type=MatchType.DICT_MATCH,
                    threshold=0,
                    weight=0.6
                ),
                dict_mappings=[]
            )
        ]
    ),
    llm_top_k=3
)
