longa_set = {
    '\u1FB1',  # ᾱ: GREEK SMALL LETTER ALPHA WITH MACRON
    '\u1FB9',  # Ᾱ: GREEK CAPITAL LETTER ALPHA WITH MACRON
    '\u03B1\u0304',  # ᾱ: GREEK SMALL LETTER ALPHA WITH MACRON
    '\u0391\u0304',  # Ᾱ: GREEK CAPITAL LETTER ALPHA WITH MACRON
    '\u1FB1\u0313',  # ᾱ̓: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING COMMA ABOVE
    '\u1FB9\u0313',  # Ᾱ̓: GREEK CAPITAL LETTER ALPHA WITH MACRON COMBINING COMMA ABOVE
    '\u1FB1\u0314',  # ᾱ̔: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING REVERSED COMMA ABOVE
    '\u1FB9\u0314',  # Ᾱ̔: GREEK CAPITAL LETTER ALPHA WITH MACRON COMBINING REVERSED COMMA ABOVE
    '\u1FB1\u0301',  # ᾱ́: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING ACUTE ACCENT
    '\u1FB1\u0300',  # ᾱ̀: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING GRAVE ACCENT
    '\u1FB1\u0345',  # ᾱͅ: GREEK SMALL LETTER ALPHA WITH MACRON COMBINING YPOGEGRAMMENI
    '\u1FD1',  # ῑ: GREEK SMALL LETTER IOTA WITH MACRON
    '\u1FD9',  # Ῑ: GREEK CAPITAL LETTER IOTA WITH MACRON
    '\u03B9\u0304',  # ῑ: GREEK SMALL LETTER IOTA WITH MACRON
    '\u0399\u0304',  # Ῑ: GREEK CAPITAL LETTER IOTA WITH MACRON
    '\u1FD1\u0313',  # ῑ̓: GREEK SMALL LETTER IOTA WITH MACRON COMBINING COMMA ABOVE
    '\u1FD9\u0313',  # Ῑ̓: GREEK CAPITAL LETTER IOTA WITH MACRON COMBINING COMMA ABOVE
    '\u1FD1\u0314',  # ῑ̔: GREEK SMALL LETTER IOTA WITH MACRON COMBINING REVERSED COMMA ABOVE
    '\u1FD9\u0314',  # Ῑ̔: GREEK CAPITAL LETTER IOTA WITH MACRON COMBINING REVERSED COMMA ABOVE
    '\u1FD1\u0301',  # ῑ́: GREEK SMALL LETTER IOTA WITH MACRON COMBINING ACUTE ACCENT
    '\u1FD1\u0308',  # ῑ̈: GREEK SMALL LETTER IOTA WITH MACRON COMBINING DIAERESIS

    '\u1FE1',  # ῡ: GREEK SMALL LETTER UPSILON WITH MACRON
    '\u1FE9',  # Ῡ: GREEK CAPITAL LETTER UPSILON WITH MACRON
    '\u03C5\u0304',  # ῡ: GREEK SMALL LETTER UPSILON WITH MACRON
    '\u03A5\u0304',  # Ῡ: GREEK CAPITAL LETTER UPSILON WITH MACRON
    '\u1FE1\u0314',  # ῡ̔: GREEK SMALL LETTER UPSILON WITH MACRON COMBINING REVERSED COMMA ABOVE
    '\u1FE9\u0314',  # Ῡ̔: GREEK CAPITAL LETTER UPSILON WITH MACRON COMBINING REVERSED COMMA ABOVE
    '\u1FE1\u0301',  # ῡ́: GREEK SMALL LETTER UPSILON WITH MACRON COMBINING ACUTE ACCENT
    '\u1FE1\u0308',  # ῡ̈: GREEK SMALL LETTER UPSILON WITH MACRON COMBINING DIAERESIS
}