from typing import List, Dict, Any
from ..DetectorEvent import Track

def print_validation_summary(py_events: List[Dict[str, Any]], py_tracks: List[Track], verbose: bool) -> None: ...
def compute_tracking_efficiency(py_events: List[Dict[str, Any]], py_tracks: List[Track], particle_type: str) -> float: ...
def export_validation_to_json(py_events: List[Dict[str, Any]], py_tracks: List[Track], verbose: bool) -> Dict[str, Any]: ...
def export_detailed_metrics_json(py_events: List[Dict[str, Any]], py_tracks: List[Track], verbose: bool) -> Dict[str, Any]: ...