"""Save file loading and parsing modules"""

from .parser import SaveParser, load_savefile, load_savefile_from_bytes
from .reader import BinaryReader, ChunkType, SaveLoadType
from .formatter import (
    convert_date_to_year,
    convert_date_to_ymd,
    format_inflation_value,
    format_company_data,
)
from .models import (
    SaveFileData,
    GameMeta,
    GameData,
    MapData,
    CompanyData,
    VehicleData,
    IndustryData,
    TownData,
    StationData,
    CargoPacketData,
    TileData,
    SignData,
    OrderData,
    DepotData,
    EngineData,
    GroupData,
    GoalData,
    StoryPageData,
    LeagueTableData,
    AIData,
    GameLogData,
    NewGRFData,
    AnimatedTileData,
    LinkGraphData,
    AirportData,
    ObjectData,
    PersistentStorageData,
    WaterRegionData,
    RandomizerData,
    VehicleType,
    CargoType,
    IndustryType,
    DateInfo,
    InflationInfo,
)
from .exporter import SaveFileExporter, export_savefile_to_json, export_savefile_to_string
from .map_flatbuffers import build_map_flatbuffer, MapFB
from .tiles import (
    decode_tile_type,
    decode_owner,
    decode_industry_info,
    owner_display,
    industry_type_display,
)

__all__ = [
    # Core
    "SaveParser",
    "load_savefile",
    "load_savefile_from_bytes",
    "BinaryReader",
    "ChunkType",
    "SaveLoadType",
    # Formatters
    "convert_date_to_year",
    "convert_date_to_ymd",
    "format_inflation_value",
    "format_company_data",
    # Models
    "SaveFileData",
    "GameMeta",
    "GameData",
    "MapData",
    "CompanyData",
    "VehicleData",
    "IndustryData",
    "TownData",
    "StationData",
    "CargoPacketData",
    "TileData",
    "SignData",
    "OrderData",
    "DepotData",
    "EngineData",
    "GroupData",
    "GoalData",
    "StoryPageData",
    "LeagueTableData",
    "AIData",
    "GameLogData",
    "NewGRFData",
    "AnimatedTileData",
    "LinkGraphData",
    "AirportData",
    "ObjectData",
    "PersistentStorageData",
    "WaterRegionData",
    "RandomizerData",
    # Enums
    "VehicleType",
    "CargoType",
    "IndustryType",
    "DateInfo",
    "InflationInfo",
    # Exporters
    "SaveFileExporter",
    "export_savefile_to_json",
    "export_savefile_to_string",
    # FlatBuffers map
    "build_map_flatbuffer",
    "MapFB",
    # Tile helpers
    "decode_tile_type",
    "decode_owner",
    "decode_industry_info",
    "owner_display",
    "industry_type_display",
]
