from typing import Literal
from enum import Enum


class DeviceType(Enum):
    CPU_FULL_AMPLITUDE_SIMULATOR = 1
    CPU_NOISY_SIMULATOR = 2
    CPU_SINGLE_AMPLITUDE_SIMULATOR = 3
    CPU_PARTIAL_AMPLITUDE_SIMULATOR = 4
    GPU_FULL_AMPLITUDE_SIMULATOR = 10
    GPU_NOISY_SIMULATOR = 11
    GPU_SINGLE_AMPLITUDE_SIMULATOR = 12
    GPU_PARTIAL_AMPLITUDE_SIMULATOR = 13
    NPU_FULL_AMPLITUDE_SIMULATOR = 20
    NPU_NOISY_SIMULATOR = 21
    NPU_SINGLE_AMPLITUDE_SIMULATOR = 22
    NPU_PARTIAL_AMPLITUDE_SIMULATOR = 23
    SUPERCONDUCTING_QUANTUM_COMPUTER = 40


ChannelType = Literal[
    "CPU_FULL_AMPLITUDE_SIMULATOR",
    "CPU_NOISY_SIMULATOR",
    "CPU_SINGLE_AMPLITUDE_SIMULATOR",
    "CPU_PARTIAL_AMPLITUDE_SIMULATOR",
    "GPU_FULL_AMPLITUDE_SIMULATOR",
    "GPU_NOISY_SIMULATOR",
    "GPU_SINGLE_AMPLITUDE_SIMULATOR",
    "GPU_PARTIAL_AMPLITUDE_SIMULATOR",
    "NPU_FULL_AMPLITUDE_SIMULATOR",
    "NPU_NOISY_SIMULATOR",
    "NPU_SINGLE_AMPLITUDE_SIMULATOR",
    "NPU_PARTIAL_AMPLITUDE_SIMULATOR",
    "SUPERCONDUCTING_QUANTUM_COMPUTER"
]
