import pandas as pd

fal_data = [
    {
        "field_name": "record_id",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Probanden-ID",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_datum",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Datum",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "date_ymd",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_alter",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "1. Wie alt sind Sie? (Jahre)",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "120",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_haendigkeit",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "2. Sind Sie",
        "choices": "1, rechtshändig | 2, linkshändig | 3, beidhändig",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_geschlecht",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "3. Geschlecht",
        "choices": "1, männlich | 2, weiblich | 3, anderes",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_schulabschluss",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "4. Welchen Schulabschluss haben Sie?",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_taetigkeit",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "5. Welcher Tätigkeit gehen Sie z.Zt. nach?",
        "choices": "1, Studium | 2, berufstätig | 3, nicht berufstätig",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_studium_fachrichtung",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Fachrichtung (falls Studium)",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_taetigkeit]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_beruf",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Beruf (falls berufstätig)",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_taetigkeit]='2'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_schlafdauer",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Wie viele Stunden haben Sie letzte Nacht geschlafen? (Stunden)",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "24",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_schlafdauer_bewertung",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "7. Diese Schlafdauer war für mich",
        "choices": "1, normal | 2, eher lang | 3, viel zu kurz, ich bin ziemlich müde",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_alkohol",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "8. Haben Sie gestern Alkohol getrunken?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_alkohol_menge",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, bitte Menge angeben",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_alkohol]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_raucher",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "9. Falls Sie Raucher sind: Haben Sie heute",
        "choices": "1, sehr viel | 2, normal | 3, wenig / gar nicht geraucht",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_koffein",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "10. Falls Sie Kaffee, Tee oder Cola trinken: Haben Sie heute",
        "choices": "1, sehr viel | 2, normal | 3, wenig/keine koffeinhaltigen Getränke getrunken",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_letzte_mahlzeit",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "11. Vor wie vielen Stunden haben Sie zum letzten Mal gegessen?",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "48",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_neuro",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "12. Sind Sie z.Zt. in neurologischer, psychiatrischer oder psychologischer Behandlung?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_neuro_grund",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, wegen",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_behandlung_neuro]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_neuro_frueher",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "13. Waren Sie bereits früher einmal in neurologischer, psychiatrischer oder psychologischer Behandlung?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_neuro_frueher_grund",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, wegen",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_behandlung_neuro_frueher]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_aerztlich",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "14. Sind Sie z.Zt. in ärztlicher Behandlung (außer beim Neurologen/ Psychiater)?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_aerztlich_grund",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, wegen",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_behandlung_aerztlich]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_medikamente",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "15. Nehmen Sie z.Zt. Medikamente ein?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_medikamente_details",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, bitte angeben",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_medikamente]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_drogen",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "16. Nehmen Sie Drogen oder haben Sie schon mal regelmäßig Drogen genommen?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_drogen_details",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, bitte angeben",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_drogen]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_studien_mv",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "17. Haben Sie bereits an Studien zur Bewegungsvorstellung teilgenommen?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_studien_mv_details",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, bitte angeben",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_studien_mv]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_mv_technik",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "18. Haben Sie bereits Bewegungsvorstellungstechniken genutzt, um eine Tätigkeit zu erlernen oder zu verbessern? (Sport, Instrumente o.ä.)",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_mv_technik_details",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, bitte angeben",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_mv_technik]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_instrument",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "19. Spielen Sie ein Instrument? Wenn ja, welches? Wie lange schon? Wie oft spielen Sie in der Woche?",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_sport",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "20. Treiben Sie regelmäßig Sport? Wenn ja, welche Sportarten? Wie lange schon? Wie oft betreibst Du diesen Sport in der Woche? (Bei Mehrfachantworten alles gesondert notieren!)",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    }
]

fal = pd.DataFrame(fal_data)

ehi_data = [
    {
        "field_name": "ehi_schreiben",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "1. Schreiben",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_zeichnen",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "2. Zeichnen",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_werfen",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "3. Werfen",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_schere",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "4. Schere",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_zahnbuerste",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "5. Zahnbürste",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_messer",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "6. Messer (ohne Gabel)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_loeffel",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "7. Löffel",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_besen",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "8. Besen (obere Hand)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_streichholz",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "9. Streichholz anzünden (Streichholz)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_kiste",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "10. Öffnen einer Kiste (Deckel)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
]
ehi = pd.DataFrame(ehi_data)

# BDI-II item texts from the official German version (Kurzform, Beck et al. 1996)
bdi_ii_items = [
    "Ich bin nicht traurig. | Ich bin traurig. | Ich bin ständig traurig und kann mich nicht davon lösen. | Ich bin so traurig oder unglücklich, dass ich es nicht mehr aushalte.",
    "Ich sehe nicht besonders schwarz für die Zukunft. | Ich sehe schwarz für die Zukunft. | Ich fühle, dass nichts mehr gut werden kann. | Ich habe das Gefühl, dass meine Zukunft hoffnungslos ist und sich nichts bessern kann.",
    "Ich habe nicht das Gefühl, ein Versager zu sein. | Ich habe öfter das Gefühl, versagt zu haben. | Wenn ich auf mein Leben zurückblicke, sehe ich nur viele Misserfolge. | Ich habe das Gefühl, als völliger Versager zu sein.",
    "Ich bin mit mir und meinem Leben zufrieden. | Ich bin nicht mehr so zufrieden wie früher. | Ich bin mit mir und meinem Leben unzufrieden. | Ich bin völlig unzufrieden mit mir und meinem Leben.",
    "Ich fühle mich nicht besonders schuldig. | Ich fühle mich öfter schuldig. | Ich fühle mich die meiste Zeit schuldig. | Ich fühle mich ständig schuldig.",
    "Ich fühle mich nicht bestraft. | Ich fühle mich manchmal bestraft. | Ich fühle mich oft bestraft. | Ich fühle mich ständig bestraft.",
    "Ich bin mit mir selbst zufrieden. | Ich bin mit mir selbst unzufrieden. | Ich verachte mich selbst. | Ich hasse mich selbst.",
    "Ich kritisiere mich nicht mehr als sonst. | Ich kritisiere mich mehr als früher. | Ich kritisiere mich ständig. | Ich kritisiere mich für alles, was ich tue.",
    "Ich habe keine Selbstmordgedanken. | Ich habe manchmal Selbstmordgedanken, würde sie aber nicht ausführen. | Ich habe öfter Selbstmordgedanken. | Ich würde mich am liebsten umbringen, wenn ich die Gelegenheit hätte.",
    "Ich weine nicht mehr als sonst. | Ich weine jetzt öfter als früher. | Ich weine jetzt ständig. | Früher konnte ich weinen, jetzt kann ich es nicht mehr, auch wenn ich möchte.",
    "Ich bin nicht unruhiger als sonst. | Ich bin manchmal unruhig oder nervös. | Ich bin oft unruhig oder nervös. | Ich bin ständig unruhig oder nervös.",
    "Ich habe mein Interesse an anderen Menschen oder Aktivitäten nicht verloren. | Ich habe weniger Interesse an anderen Menschen oder Aktivitäten als früher. | Ich habe fast alles Interesse an anderen Menschen oder Aktivitäten verloren. | Ich habe das Interesse an anderen Menschen oder Aktivitäten völlig verloren.",
    "Ich kann Entscheidungen genauso gut treffen wie früher. | Ich habe mehr Schwierigkeiten, Entscheidungen zu treffen als früher. | Ich habe große Schwierigkeiten, Entscheidungen zu treffen. | Ich kann überhaupt keine Entscheidungen mehr treffen.",
    "Ich fühle mich nicht wertlos. | Ich fühle mich weniger wertvoll als früher. | Ich fühle mich wertlos. | Ich fühle mich völlig wertlos.",
    "Ich habe genauso viel Energie wie früher. | Ich habe weniger Energie als früher. | Ich habe viel weniger Energie als früher. | Ich habe überhaupt keine Energie mehr.",
    "Ich habe keine Schlafprobleme. | Ich schlafe schlechter als früher. | Ich wache nachts oft auf und habe Schwierigkeiten, wieder einzuschlafen. | Ich kann kaum noch schlafen.",
    "Ich bin nicht reizbarer als sonst. | Ich bin leichter reizbar als früher. | Ich bin viel reizbarer als früher. | Ich bin ständig gereizt.",
    "Mein Appetit ist nicht schlechter als sonst. | Mein Appetit ist schlechter als früher. | Mein Appetit ist jetzt viel schlechter. | Ich habe überhaupt keinen Appetit mehr.",
    "Ich kann mich genauso gut konzentrieren wie früher. | Ich kann mich nicht mehr so gut konzentrieren wie früher. | Ich habe große Schwierigkeiten, mich zu konzentrieren. | Ich kann mich überhaupt nicht mehr konzentrieren.",
    "Ich bin nicht müder oder erschöpfter als sonst. | Ich bin schneller müde oder erschöpft als früher. | Ich bin fast immer müde oder erschöpft. | Ich bin ständig müde oder erschöpft.",
    "Ich habe mein Interesse an Sexualität nicht verloren. | Ich habe weniger Interesse an Sexualität als früher. | Ich habe fast alles Interesse an Sexualität verloren. | Ich habe das Interesse an Sexualität völlig verloren."
]

bdi_ii_item_names = [
    "Traurigkeit",
    "Pessimismus",
    "Versagensgefühle",
    "Unzufriedenheit",
    "Schuldgefühle",
    "Gefühle von Bestrafung",
    "Selbstablehnung",
    "Selbstkritik",
    "Suizidgedanken oder -wünsche",
    "Weinen",
    "Unruhe",
    "Verlust von Interesse",
    "Entscheidungsschwierigkeiten",
    "Wertlosigkeitsgefühle",
    "Verlust von Energie",
    "Schlafstörungen",
    "Reizbarkeit",
    "Veränderungen des Appetits",
    "Konzentrationsschwierigkeiten",
    "Müdigkeit oder Erschöpfung",
    "Verlust des Interesses an Sexualität"
]

bdi_ii_data = [
    {
        "field_name": f"bdi_ii_{i+1}_{bdi_ii_item_names[i].lower().replace(' ', '_')}",
        "form_name": "bdi_ii",
        "section_header": "",
        "field_type": "radio",
        "field_label": f"{i+1}.",
        "choices": " | ".join([f"{j}, {option}" for j, option in enumerate(item.split(" | "))]),
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": str(i+1),
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    }
    for i, item in enumerate(bdi_ii_items)
]
bdi_ii = pd.DataFrame(bdi_ii_data)

