# Generated by Django 5.2 on 2025-05-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ai_agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="max_retries",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="tool",
            name="strict",
            field=models.BooleanField(
                default=False,
                help_text="Whether to require all parameters to be present",
            ),
        ),
    ]
