# Generated by Django 5.2.1 on 2025-05-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ag_grid", "0002_grideditlog_action_grideditlog_object_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grideditlog",
            name="object_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
