
# This file was generated by 'versioneer.py' (0.29+8.gf9bbd1b) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-26T02:44:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2deb219949ed3eab8638b286dc7d5ea4918e378",
 "version": "0.70.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
