# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: consensus_update_topic.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'consensus_update_topic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from . import basic_types_pb2 as basic__types__pb2
from . import duration_pb2 as duration__pb2
from . import timestamp_pb2 as timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63onsensus_update_topic.proto\x12\x05proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x11\x62\x61sic_types.proto\x1a\x0e\x64uration.proto\x1a\x0ftimestamp.proto\"\xaf\x02\n#ConsensusUpdateTopicTransactionBody\x12\x1f\n\x07topicID\x18\x01 \x01(\x0b\x32\x0e.proto.TopicID\x12*\n\x04memo\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12(\n\x0e\x65xpirationTime\x18\x04 \x01(\x0b\x32\x10.proto.Timestamp\x12\x1c\n\x08\x61\x64minKey\x18\x06 \x01(\x0b\x32\n.proto.Key\x12\x1d\n\tsubmitKey\x18\x07 \x01(\x0b\x32\n.proto.Key\x12(\n\x0f\x61utoRenewPeriod\x18\x08 \x01(\x0b\x32\x0f.proto.Duration\x12*\n\x10\x61utoRenewAccount\x18\t \x01(\x0b\x32\x10.proto.AccountIDB&\n\"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'consensus_update_topic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.hederahashgraph.api.proto.javaP\001'
  _globals['_CONSENSUSUPDATETOPICTRANSACTIONBODY']._serialized_start=124
  _globals['_CONSENSUSUPDATETOPICTRANSACTIONBODY']._serialized_end=427
# @@protoc_insertion_point(module_scope)
