from minjiang_client.qc.cliffords import Tw as Tw, clifford_gates as clifford_gates, clifford_gates_decom_1q as clifford_gates_decom_1q

def matrix_distance_ignore_global_phase(A, B): ...
def matrix_distance_ignore_global_phase_simple(A, B): ...
def generate_rb_sequence_1q(length): ...
def generate_rb_sequence_2q(length: int): ...
def fit_rb_curve(lengths, fidelities): ...
