# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vessl.openapi_client.configuration import Configuration


class OrmKernelClusterConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ingress': 'OrmKernelClusterConfigIngress',
        'nodes': 'OrmKernelClusterConfigNodes',
        'service': 'OrmKernelClusterConfigService',
        'service_account_name': 'str',
        'storage_class': 'OrmKernelClusterConfigStorageClass'
    }

    attribute_map = {
        'ingress': 'ingress',
        'nodes': 'nodes',
        'service': 'service',
        'service_account_name': 'service_account_name',
        'storage_class': 'storage_class'
    }

    def __init__(self, ingress=None, nodes=None, service=None, service_account_name=None, storage_class=None, local_vars_configuration=None):  # noqa: E501
        """OrmKernelClusterConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._ingress = None
        self._nodes = None
        self._service = None
        self._service_account_name = None
        self._storage_class = None
        self.discriminator = None

        if ingress is not None:
            self.ingress = ingress
        if nodes is not None:
            self.nodes = nodes
        if service is not None:
            self.service = service
        if service_account_name is not None:
            self.service_account_name = service_account_name
        if storage_class is not None:
            self.storage_class = storage_class

    @property
    def ingress(self):
        """Gets the ingress of this OrmKernelClusterConfig.  # noqa: E501


        :return: The ingress of this OrmKernelClusterConfig.  # noqa: E501
        :rtype: OrmKernelClusterConfigIngress
        """
        return self._ingress

    @ingress.setter
    def ingress(self, ingress):
        """Sets the ingress of this OrmKernelClusterConfig.


        :param ingress: The ingress of this OrmKernelClusterConfig.  # noqa: E501
        :type ingress: OrmKernelClusterConfigIngress
        """

        self._ingress = ingress

    @property
    def nodes(self):
        """Gets the nodes of this OrmKernelClusterConfig.  # noqa: E501


        :return: The nodes of this OrmKernelClusterConfig.  # noqa: E501
        :rtype: OrmKernelClusterConfigNodes
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes):
        """Sets the nodes of this OrmKernelClusterConfig.


        :param nodes: The nodes of this OrmKernelClusterConfig.  # noqa: E501
        :type nodes: OrmKernelClusterConfigNodes
        """

        self._nodes = nodes

    @property
    def service(self):
        """Gets the service of this OrmKernelClusterConfig.  # noqa: E501


        :return: The service of this OrmKernelClusterConfig.  # noqa: E501
        :rtype: OrmKernelClusterConfigService
        """
        return self._service

    @service.setter
    def service(self, service):
        """Sets the service of this OrmKernelClusterConfig.


        :param service: The service of this OrmKernelClusterConfig.  # noqa: E501
        :type service: OrmKernelClusterConfigService
        """

        self._service = service

    @property
    def service_account_name(self):
        """Gets the service_account_name of this OrmKernelClusterConfig.  # noqa: E501


        :return: The service_account_name of this OrmKernelClusterConfig.  # noqa: E501
        :rtype: str
        """
        return self._service_account_name

    @service_account_name.setter
    def service_account_name(self, service_account_name):
        """Sets the service_account_name of this OrmKernelClusterConfig.


        :param service_account_name: The service_account_name of this OrmKernelClusterConfig.  # noqa: E501
        :type service_account_name: str
        """

        self._service_account_name = service_account_name

    @property
    def storage_class(self):
        """Gets the storage_class of this OrmKernelClusterConfig.  # noqa: E501


        :return: The storage_class of this OrmKernelClusterConfig.  # noqa: E501
        :rtype: OrmKernelClusterConfigStorageClass
        """
        return self._storage_class

    @storage_class.setter
    def storage_class(self, storage_class):
        """Sets the storage_class of this OrmKernelClusterConfig.


        :param storage_class: The storage_class of this OrmKernelClusterConfig.  # noqa: E501
        :type storage_class: OrmKernelClusterConfigStorageClass
        """

        self._storage_class = storage_class

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrmKernelClusterConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrmKernelClusterConfig):
            return True

        return self.to_dict() != other.to_dict()
