# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vessl.openapi_client.configuration import Configuration


class RunExecutionVolumeV2CreateAPIInput(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'origin_path': 'str',
        'storage_name': 'str',
        'volume_name': 'str'
    }

    attribute_map = {
        'origin_path': 'origin_path',
        'storage_name': 'storage_name',
        'volume_name': 'volume_name'
    }

    def __init__(self, origin_path=None, storage_name=None, volume_name=None, local_vars_configuration=None):  # noqa: E501
        """RunExecutionVolumeV2CreateAPIInput - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._origin_path = None
        self._storage_name = None
        self._volume_name = None
        self.discriminator = None

        self.origin_path = origin_path
        self.storage_name = storage_name
        self.volume_name = volume_name

    @property
    def origin_path(self):
        """Gets the origin_path of this RunExecutionVolumeV2CreateAPIInput.  # noqa: E501


        :return: The origin_path of this RunExecutionVolumeV2CreateAPIInput.  # noqa: E501
        :rtype: str
        """
        return self._origin_path

    @origin_path.setter
    def origin_path(self, origin_path):
        """Sets the origin_path of this RunExecutionVolumeV2CreateAPIInput.


        :param origin_path: The origin_path of this RunExecutionVolumeV2CreateAPIInput.  # noqa: E501
        :type origin_path: str
        """
        if self.local_vars_configuration.client_side_validation and origin_path is None:  # noqa: E501
            raise ValueError("Invalid value for `origin_path`, must not be `None`")  # noqa: E501

        self._origin_path = origin_path

    @property
    def storage_name(self):
        """Gets the storage_name of this RunExecutionVolumeV2CreateAPIInput.  # noqa: E501


        :return: The storage_name of this RunExecutionVolumeV2CreateAPIInput.  # noqa: E501
        :rtype: str
        """
        return self._storage_name

    @storage_name.setter
    def storage_name(self, storage_name):
        """Sets the storage_name of this RunExecutionVolumeV2CreateAPIInput.


        :param storage_name: The storage_name of this RunExecutionVolumeV2CreateAPIInput.  # noqa: E501
        :type storage_name: str
        """
        if self.local_vars_configuration.client_side_validation and storage_name is None:  # noqa: E501
            raise ValueError("Invalid value for `storage_name`, must not be `None`")  # noqa: E501

        self._storage_name = storage_name

    @property
    def volume_name(self):
        """Gets the volume_name of this RunExecutionVolumeV2CreateAPIInput.  # noqa: E501


        :return: The volume_name of this RunExecutionVolumeV2CreateAPIInput.  # noqa: E501
        :rtype: str
        """
        return self._volume_name

    @volume_name.setter
    def volume_name(self, volume_name):
        """Sets the volume_name of this RunExecutionVolumeV2CreateAPIInput.


        :param volume_name: The volume_name of this RunExecutionVolumeV2CreateAPIInput.  # noqa: E501
        :type volume_name: str
        """
        if self.local_vars_configuration.client_side_validation and volume_name is None:  # noqa: E501
            raise ValueError("Invalid value for `volume_name`, must not be `None`")  # noqa: E501

        self._volume_name = volume_name

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RunExecutionVolumeV2CreateAPIInput):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RunExecutionVolumeV2CreateAPIInput):
            return True

        return self.to_dict() != other.to_dict()
