# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vessl.openapi_client.configuration import Configuration


class SamlRequestedAttribute(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'friendly_name': 'str',
        'is_required': 'bool',
        'name': 'str',
        'name_format': 'str',
        'values': 'list[SamlAttributeValue]'
    }

    attribute_map = {
        'friendly_name': 'FriendlyName',
        'is_required': 'IsRequired',
        'name': 'Name',
        'name_format': 'NameFormat',
        'values': 'Values'
    }

    def __init__(self, friendly_name=None, is_required=None, name=None, name_format=None, values=None, local_vars_configuration=None):  # noqa: E501
        """SamlRequestedAttribute - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._friendly_name = None
        self._is_required = None
        self._name = None
        self._name_format = None
        self._values = None
        self.discriminator = None

        if friendly_name is not None:
            self.friendly_name = friendly_name
        self.is_required = is_required
        if name is not None:
            self.name = name
        if name_format is not None:
            self.name_format = name_format
        if values is not None:
            self.values = values

    @property
    def friendly_name(self):
        """Gets the friendly_name of this SamlRequestedAttribute.  # noqa: E501


        :return: The friendly_name of this SamlRequestedAttribute.  # noqa: E501
        :rtype: str
        """
        return self._friendly_name

    @friendly_name.setter
    def friendly_name(self, friendly_name):
        """Sets the friendly_name of this SamlRequestedAttribute.


        :param friendly_name: The friendly_name of this SamlRequestedAttribute.  # noqa: E501
        :type friendly_name: str
        """

        self._friendly_name = friendly_name

    @property
    def is_required(self):
        """Gets the is_required of this SamlRequestedAttribute.  # noqa: E501


        :return: The is_required of this SamlRequestedAttribute.  # noqa: E501
        :rtype: bool
        """
        return self._is_required

    @is_required.setter
    def is_required(self, is_required):
        """Sets the is_required of this SamlRequestedAttribute.


        :param is_required: The is_required of this SamlRequestedAttribute.  # noqa: E501
        :type is_required: bool
        """

        self._is_required = is_required

    @property
    def name(self):
        """Gets the name of this SamlRequestedAttribute.  # noqa: E501


        :return: The name of this SamlRequestedAttribute.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SamlRequestedAttribute.


        :param name: The name of this SamlRequestedAttribute.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def name_format(self):
        """Gets the name_format of this SamlRequestedAttribute.  # noqa: E501


        :return: The name_format of this SamlRequestedAttribute.  # noqa: E501
        :rtype: str
        """
        return self._name_format

    @name_format.setter
    def name_format(self, name_format):
        """Sets the name_format of this SamlRequestedAttribute.


        :param name_format: The name_format of this SamlRequestedAttribute.  # noqa: E501
        :type name_format: str
        """

        self._name_format = name_format

    @property
    def values(self):
        """Gets the values of this SamlRequestedAttribute.  # noqa: E501


        :return: The values of this SamlRequestedAttribute.  # noqa: E501
        :rtype: list[SamlAttributeValue]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this SamlRequestedAttribute.


        :param values: The values of this SamlRequestedAttribute.  # noqa: E501
        :type values: list[SamlAttributeValue]
        """

        self._values = values

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SamlRequestedAttribute):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SamlRequestedAttribute):
            return True

        return self.to_dict() != other.to_dict()
