# coding: utf-8

"""
    Aron API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vessl.openapi_client.configuration import Configuration


class V1ServeRevisionWorkerForm(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'env': 'dict[str, V1EnvForm]',
        'image': 'V1ImageForm',
        '_import': 'dict[str, V1ImportForm]',
        'mount': 'dict[str, V1MountForm]',
        'ports': 'list[V1PortForm]',
        'resources': 'V1ResourcesForm',
        'run': 'list[V1Command]',
        'service_account': 'V1ServiceAccountForm'
    }

    attribute_map = {
        'env': 'env',
        'image': 'image',
        '_import': 'import',
        'mount': 'mount',
        'ports': 'ports',
        'resources': 'resources',
        'run': 'run',
        'service_account': 'service_account'
    }

    def __init__(self, env=None, image=None, _import=None, mount=None, ports=None, resources=None, run=None, service_account=None, local_vars_configuration=None):  # noqa: E501
        """V1ServeRevisionWorkerForm - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._env = None
        self._image = None
        self.__import = None
        self._mount = None
        self._ports = None
        self._resources = None
        self._run = None
        self._service_account = None
        self.discriminator = None

        if env is not None:
            self.env = env
        self.image = image
        if _import is not None:
            self._import = _import
        if mount is not None:
            self.mount = mount
        self.ports = ports
        self.resources = resources
        if run is not None:
            self.run = run
        if service_account is not None:
            self.service_account = service_account

    @property
    def env(self):
        """Gets the env of this V1ServeRevisionWorkerForm.  # noqa: E501


        :return: The env of this V1ServeRevisionWorkerForm.  # noqa: E501
        :rtype: dict[str, V1EnvForm]
        """
        return self._env

    @env.setter
    def env(self, env):
        """Sets the env of this V1ServeRevisionWorkerForm.


        :param env: The env of this V1ServeRevisionWorkerForm.  # noqa: E501
        :type env: dict[str, V1EnvForm]
        """

        self._env = env

    @property
    def image(self):
        """Gets the image of this V1ServeRevisionWorkerForm.  # noqa: E501


        :return: The image of this V1ServeRevisionWorkerForm.  # noqa: E501
        :rtype: V1ImageForm
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this V1ServeRevisionWorkerForm.


        :param image: The image of this V1ServeRevisionWorkerForm.  # noqa: E501
        :type image: V1ImageForm
        """
        if self.local_vars_configuration.client_side_validation and image is None:  # noqa: E501
            raise ValueError("Invalid value for `image`, must not be `None`")  # noqa: E501

        self._image = image

    @property
    def _import(self):
        """Gets the _import of this V1ServeRevisionWorkerForm.  # noqa: E501


        :return: The _import of this V1ServeRevisionWorkerForm.  # noqa: E501
        :rtype: dict[str, V1ImportForm]
        """
        return self.__import

    @_import.setter
    def _import(self, _import):
        """Sets the _import of this V1ServeRevisionWorkerForm.


        :param _import: The _import of this V1ServeRevisionWorkerForm.  # noqa: E501
        :type _import: dict[str, V1ImportForm]
        """

        self.__import = _import

    @property
    def mount(self):
        """Gets the mount of this V1ServeRevisionWorkerForm.  # noqa: E501


        :return: The mount of this V1ServeRevisionWorkerForm.  # noqa: E501
        :rtype: dict[str, V1MountForm]
        """
        return self._mount

    @mount.setter
    def mount(self, mount):
        """Sets the mount of this V1ServeRevisionWorkerForm.


        :param mount: The mount of this V1ServeRevisionWorkerForm.  # noqa: E501
        :type mount: dict[str, V1MountForm]
        """

        self._mount = mount

    @property
    def ports(self):
        """Gets the ports of this V1ServeRevisionWorkerForm.  # noqa: E501


        :return: The ports of this V1ServeRevisionWorkerForm.  # noqa: E501
        :rtype: list[V1PortForm]
        """
        return self._ports

    @ports.setter
    def ports(self, ports):
        """Sets the ports of this V1ServeRevisionWorkerForm.


        :param ports: The ports of this V1ServeRevisionWorkerForm.  # noqa: E501
        :type ports: list[V1PortForm]
        """
        if self.local_vars_configuration.client_side_validation and ports is None:  # noqa: E501
            raise ValueError("Invalid value for `ports`, must not be `None`")  # noqa: E501

        self._ports = ports

    @property
    def resources(self):
        """Gets the resources of this V1ServeRevisionWorkerForm.  # noqa: E501


        :return: The resources of this V1ServeRevisionWorkerForm.  # noqa: E501
        :rtype: V1ResourcesForm
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this V1ServeRevisionWorkerForm.


        :param resources: The resources of this V1ServeRevisionWorkerForm.  # noqa: E501
        :type resources: V1ResourcesForm
        """
        if self.local_vars_configuration.client_side_validation and resources is None:  # noqa: E501
            raise ValueError("Invalid value for `resources`, must not be `None`")  # noqa: E501

        self._resources = resources

    @property
    def run(self):
        """Gets the run of this V1ServeRevisionWorkerForm.  # noqa: E501


        :return: The run of this V1ServeRevisionWorkerForm.  # noqa: E501
        :rtype: list[V1Command]
        """
        return self._run

    @run.setter
    def run(self, run):
        """Sets the run of this V1ServeRevisionWorkerForm.


        :param run: The run of this V1ServeRevisionWorkerForm.  # noqa: E501
        :type run: list[V1Command]
        """

        self._run = run

    @property
    def service_account(self):
        """Gets the service_account of this V1ServeRevisionWorkerForm.  # noqa: E501


        :return: The service_account of this V1ServeRevisionWorkerForm.  # noqa: E501
        :rtype: V1ServiceAccountForm
        """
        return self._service_account

    @service_account.setter
    def service_account(self, service_account):
        """Sets the service_account of this V1ServeRevisionWorkerForm.


        :param service_account: The service_account of this V1ServeRevisionWorkerForm.  # noqa: E501
        :type service_account: V1ServiceAccountForm
        """

        self._service_account = service_account

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1ServeRevisionWorkerForm):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1ServeRevisionWorkerForm):
            return True

        return self.to_dict() != other.to_dict()
