
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-08-18T16:11:41-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "95e0163e56ba16a721307ceace92260e4ffe637e",
 "version": "2025.8.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
