from _typeshed import Incomplete

ALL_EXTENSIONS: str
DEFAULT_AZURE_OPENAI_API_VERSION: str
DOCUMENT_MIME_TYPES: Incomplete
GOOGLE_SCOPES: Incomplete
HEX_REPR_LENGTH: int
MESSAGE_TUPLE_LENGTH: int
DEFAULT_CONTENT_PLACEHOLDER_TYPE: str
HTTP_STATUS_CODE_PATTERNS: Incomplete
