
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-08-21T09:45:59+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "31a8924acade007cb09a20e5adcba5ae8e11062c",
 "version": "2.3.0a23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
