from enum import Enum
from typing import IO, Any, Callable

def load_json(fp): ...
def save_json(fp, obj): ...
def load_yaml(fp): ...
def save_yaml(fp, obj): ...

class Format(Enum):
    JSON: Format
    YAML: Format

    def __init__(self, extension: str, load_callback: Callable[[IO[Any]], Any], save_callback: Callable[[IO[Any], Any], None]): ...

    def load(self, fp): ...
    
    def save(self, fp, obj): ...
