from django.utils.text import slugify


notes: list[tuple[str, str]] = [
    ('wrk', 'Work'),
    ('std', 'Study'),
    ('cmt', 'Commitment'),
    ('fml', 'Family'),
    ('hlt', 'Health'),
    ('fin', 'Finance'),
    ('trv', 'Travel'),
    ('vol', 'Volunteer'),
    ('rel', 'Religious'),
    ('leg', 'Legal'),
]

cards_types: list[tuple[str, str]] = [
    ('deb', 'Debit'),
    ('cred', 'Credit'),
    ('pre', 'Prepaid'),
    ('co', 'Co-branded'),
]

banks: list[str] = [
    'ABN Amro',
    'AMP Limited',
    'ANZ Bank New Zealand',
    'Absa Bank Group',
    'Access Bank Plc',
    'Agricultural Bank of China',
    'Ally Financial',
    'American Express National Bank',
    'Attijariwafa Bank',
    'Australia and New Zealand Banking Group',
    'Axis Bank',
    'BNP Paribas',
    'Banco Original',
    'Banco Santander',
    'Banco do Brasil',
    'Bangkok Bank',
    'Bank of America',
    'Bank of China',
    'Bank of Queensland',
    'Banque Misr',
    'Barclays',
    'Bendigo and Adelaide Bank',
    'Bradesco',
    'C6 Bank',
    'Caixa',
    'Capital One',
    'Capitec Bank',
    'China Construction Bank',
    'Citibank Australia',
    'Citigroup',
    'Citizens Bank',
    'Commercial International Bank of Egypt',
    'Commerzbank',
    'Commonwealth Bank',
    'Credit Suisse',
    'Credit Suisse Australia',
    'Crédit Agricole',
    'DBS Group Holdings',
    'Danske Bank',
    'Deutsche Bank',
    'Deutsche Bank Australia',
    'Ecobank Transnational Incorporated',
    'Fifth Third Bank',
    'First City Monument Bank',
    'FirstRand Limited',
    'Goldman Sachs',
    'Guaranty Trust Bank',
    'HDFC Bank',
    'HSBC',
    'ICICI Bank',
    'ING Bank Australia',
    'ING Group',
    'Industrial and Commercial Bank of China',
    'Intesa Sanpaolo',
    'Investec',
    'Itaú',
    'JPMorgan Australia',
    'JPMorgan Chase',
    'KBC Financial Group',
    'Kasikornbank',
    'KeyCorp',
    'Latitude Financial Services',
    'Liberty Financial Group',
    'Lloyds Banking Group',
    'M&T Bank',
    'MMI Holdings',
    'Macquarie Group',
    'Malayan Banking Berhad (Maybank)',
    'Mercado Pago',
    'Mitsubishi UFJ Financial Group',
    'Mizuho Financial Group',
    'Morgan Stanley',
    'National Australia Bank',
    'National Bank of Egypt',
    'Nedbank Group',
    'Next',
    'Nordea',
    'Nubank',
    'Old Mutual Limited',
    'Oversea-Chinese Banking Corporation',
    'PNC Financial Services',
    'PagSeguro',
    'PayPal',
    'Pepper Money',
    'PicPay',
    'Pão de Açúcar',
    'Regions Financial Corporation',
    'Remgro Limited',
    'Resimac',
    'Royal Bank of Scotland',
    'Sanlam Limited',
    'Santander',
    'Siam Commercial Bank',
    'Skandinaviska Enskilda Banken',
    'Société Générale',
    'Standard Bank Group',
    'State Bank of India',
    'State Street',
    'Sumitomo Mitsui Financial Group',
    'SunTrust Banks',
    'Suncorp Group',
    'Svenska Handelsbanken',
    'TD Bank',
    'The Bank of New York Mellon',
    'Ticket',
    'U.S. Bancorp',
    'UBS',
    'UniCredit',
    'United Bank for Africa',
    'United Overseas Bank',
    'Wells Fargo',
    'Westpac',
    'Zenith Bank',
]

brands: list[str] = [
    'ANZ Rewards Visa',
    'Afriqard',
    'Airtel Money',
    'Amazon Store Card',
    'American Express',
    'American Express',
    'Apple Card',
    'BC Card',
    'BOC Cards',
    'Bancontact',
    'Bank of America',
    'Bank of Melbourne Amplify Visa',
    'Bankcard',
    'Barclays US',
    'Best Buy Credit Card',
    'CCB Cards',
    'CITIC Cards',
    'CMB Cards',
    'Capital One',
    'Carte Bancaire',
    'Chase',
    'Citibank',
    'Citibank Rewards Visa',
    'Coles Mastercard',
    'CommBank Awards Mastercard',
    'Dankort',
    'Diners Club',
    'Diners Club',
    'Diners Club',
    'Diners Club International',
    'Discover',
    'EPS Austria',
    'Elo',
    'Equitel',
    'Eurocard',
    'Forbrugsforeningskort',
    'GCash',
    'Giropay',
    'HSBC',
    'Hipercard',
    'Home Depot Credit Card',
    'Hyundai Card',
    'ICBC Cards',
    'Interswitch',
    'JCB',
    'KB Kookmin Card',
    "Kohl's Credit Card",
    'Lotte Card',
    "Lowe's Credit Card",
    'M-Pesa',
    'MB Net',
    'Macquarie Platinum Card',
    "Macy's Credit Card",
    'Maestro',
    'Mastercard',
    'Multibanco',
    'NAB Rewards Visa',
    'NIBSS Instant Payments',
    'Navy Federal Credit Union',
    'Orange Money',
    'PayAttitude',
    'PayPal Credit',
    'PesaLink',
    'PostPay',
    'PostePay',
    'Qantas American Express',
    'RSwitch',
    'RuPay',
    'SOFORT',
    'Shinhan Card',
    'SiR Direct',
    'St. George Amplify Visa',
    'Synchrony Financial',
    'Target RedCard',
    'Tigo Pesa',
    'TrueMoney',
    'USAA',
    'UnionPay',
    'VPay',
    'Verve',
    'Visa',
    'Walmart Capital One',
    'Wells Fargo',
    'Westpac Altitude Mastercard',
    'Woolworths Money',
    'Ziwapay',
    'eftpos',
    'iDEAL',
]

services: list[str] = [
    'AWS',
    'Adobe',
    'Airbnb',
    'Al-Azhar University',
    'Amazon',
    'Amazon Prime Video',
    'Ambev',
    'Americanas',
    'Amil',
    'Anhanguera',
    'Apple',
    'Assaí Atacadista',
    'Atacadão',
    'Atari',
    'Australian National University',
    'B3 (Brasil Bolsa Balcão)',
    'Banco Bradesco',
    'Banco do Brasil',
    'Blizzard Entertainment',
    'Booking',
    'C&A',
    'CMA Vantagens',
    'Cairo University',
    'California Institute of Technology',
    'Carrefour Brasil',
    'Cec Materiais de Construção',
    'Claro Brasil',
    'Columbia University',
    'Cornell University',
    'Deezer',
    'Discord',
    'Disney+',
    'Duke University',
    'ESPM',
    'ETH Zurich',
    'Epic Games',
    'Estácio',
    'Extra',
    'FGV',
    'FIA Business School',
    'Facebook',
    'Fast Shop',
    'Georgia Institute of Technology',
    'Github',
    'Glassdoor',
    'Google',
    'Gov BR',
    'Hapvida',
    'Harvard University',
    'Havan',
    'Heidelberg University',
    'Heroku',
    'IBMEC',
    'IME',
    'ITA',
    'Ibovespa',
    'Imperial College London',
    'Indeed',
    'Insper',
    'Instagram',
    'Itaú Unibanco',
    'Johns Hopkins University',
    'KU Leuven',
    'Kayak',
    "King's College London",
    'Kwai',
    'Kyoto University',
    'LG',
    'Leiden University',
    'Leroy Merlin Brasil',
    'LinkedIn',
    'Lojas Renner',
    'London School of Economics and Political Science',
    'MIT',
    'Magazine Luiza',
    'Magazine Luiza',
    'Marisa',
    'Mercado Livre',
    'Motorola',
    'Nanyang Technological University, Singapore',
    'National University of Singapore',
    'Natura &Co',
    'Netflix',
    'New York University',
    'Nintendo',
    'Northwestern University',
    'Notion',
    'Notredame Intermédica',
    'Nu Invest',
    'Boticário',
    'Oi',
    'Osaka University',
    'Outlook',
    'PUC-Rio',
    'PUC-SP',
    'Peking University',
    'Petrobras',
    'Pinterest',
    'PlayStation',
    'Polishop',
    'Porto Seguro',
    'Prevent Senior',
    'Princeton University',
    'Pão de Açúcar',
    'Reddit',
    'Revelo',
    'Riachuelo',
    'Riot Games',
    'SHEIN',
    "Sam's Club Brasil",
    'Samsung',
    'Shopee',
    'Skype',
    'Slack',
    'Spotify',
    'Stanford University',
    'Steam',
    'Stripe',
    'Submarino',
    'Sulamerica',
    'Supercell',
    'TIM Brasil',
    'Technical University of Munich',
    'Telhanorte',
    'Ticket',
    'TikTok',
    'Trello',
    'Trip Advisor',
    'Tsinghua University',
    'Twitch',
    'Twitter',
    'UFBA',
    'UFC',
    'UFMG',
    'UFPE',
    'UFPR',
    'UFRGS',
    'UFRJ',
    'UFSC',
    'UFU',
    'UNESP',
    'UNICAMP',
    'UNIP',
    'USP',
    'Unimed',
    'Uninter',
    'Universidade Anhembi Morumbi',
    'Universidade Presbiteriana Mackenzie',
    'University College London',
    'University of Amsterdam',
    'University of Bristol',
    'University of California, Berkeley',
    'University of California, Los Angeles',
    'University of California, San Diego',
    'University of Cambridge',
    'University of Cape Town',
    'University of Chicago',
    'University of Edinburgh',
    'University of Glasgow',
    'University of Manchester',
    'University of Melbourne',
    'University of Michigan',
    'University of New South Wales',
    'University of Oxford',
    'University of Pennsylvania',
    'University of Queensland',
    'University of Sydney',
    'University of Tokyo',
    'University of Warwick',
    'University of Washington',
    'University of the Witwatersrand',
    'Utrecht University',
    'Vale',
    'Vercel',
    'Via (Casas Bahia, Ponto Frio)',
    'Vivo',
    'Wargaming',
    'Wordpress',
    'Xbox',
    'Yahoo',
    'Yale University',
    'École Polytechnique Fédérale de Lausanne',
    *banks,
    *brands,
]


cards_banks: list[tuple[str, str]] = sorted(
    ((f'{slugify(i)}--', i) for i in banks), key=lambda x: x[0]
)
cards_brands: list[tuple[str, str]] = sorted(
    ((f'{slugify(i)}--', i) for i in brands), key=lambda x: x[0]
)
credentials_services: list[tuple[str, str]] = sorted(
    ((f'{slugify(i)}--', i) for i in services), key=lambda x: x[0]
)
notes_types: list[tuple[str, str]] = sorted(set(notes), key=lambda x: x[0])


cards_banks.insert(0, ('other--', 'Other'))
cards_brands.insert(0, ('other--', 'Other'))
credentials_services.insert(0, ('other--', 'Other'))
notes_types.append(('oth', 'Other'))
