# generated by datamodel-codegen:
#   filename:  properties_directory/non_scalar/total_energy_contributions.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Name(Enum):
    temperature_entropy = "temperature_entropy"


class ScalarSchema(BaseModel):
    name: Optional[Name] = None
    value: float


class Name689(Enum):
    harris_foulkes = "harris_foulkes"


class ScalarSchema83(BaseModel):
    name: Optional[Name689] = None
    value: float


class Name690(Enum):
    one_electron = "one_electron"


class ScalarSchema84(BaseModel):
    name: Optional[Name690] = None
    value: float


class Name691(Enum):
    hartree = "hartree"


class ScalarSchema85(BaseModel):
    name: Optional[Name691] = None
    value: float


class Name692(Enum):
    exchange = "exchange"


class ScalarSchema86(BaseModel):
    name: Optional[Name692] = None
    value: float


class Name693(Enum):
    exchange_correlation = "exchange_correlation"


class ScalarSchema87(BaseModel):
    name: Optional[Name693] = None
    value: float


class Name694(Enum):
    ewald = "ewald"


class ScalarSchema88(BaseModel):
    name: Optional[Name694] = None
    value: float


class Name695(Enum):
    alphaZ = "alphaZ"


class ScalarSchema89(BaseModel):
    name: Optional[Name695] = None
    value: float


class Name696(Enum):
    atomic_energy = "atomic_energy"


class ScalarSchema90(BaseModel):
    name: Optional[Name696] = None
    value: float


class Name697(Enum):
    eigenvalues = "eigenvalues"


class ScalarSchema91(BaseModel):
    name: Optional[Name697] = None
    value: float


class Name698(Enum):
    PAW_double_counting_correction_2 = "PAW_double-counting_correction_2"


class ScalarSchema92(BaseModel):
    name: Optional[Name698] = None
    value: float


class Name699(Enum):
    PAW_double_counting_correction_3 = "PAW_double-counting_correction_3"


class ScalarSchema93(BaseModel):
    name: Optional[Name699] = None
    value: float


class Name700(Enum):
    hartree_fock = "hartree_fock"


class ScalarSchema94(BaseModel):
    name: Optional[Name700] = None
    value: float


class Name701(Enum):
    total_energy_contributions = "total_energy_contributions"


class Units(Enum):
    kJ_mol = "kJ/mol"
    eV = "eV"
    J_mol = "J/mol"
    hartree = "hartree"
    cm_1 = "cm-1"
    Ry = "Ry"
    eV_atom = "eV/atom"


class TotalEnergyContributionsSchema(BaseModel):
    temperatureEntropy: Optional[ScalarSchema] = Field(None, title="scalar schema")
    """
    product of temperature and configurational entropy
    """
    harrisFoulkes: Optional[ScalarSchema83] = Field(None, title="scalar schema")
    """
    non self-consitent energy based on an input charge density
    """
    oneElectron: Optional[ScalarSchema84] = Field(None, title="scalar schema")
    """
    kinetic + pseudopotential energy
    """
    hartree: Optional[ScalarSchema85] = Field(None, title="scalar schema")
    """
    energy due to coulomb potential
    """
    exchange: Optional[ScalarSchema86] = Field(None, title="scalar schema")
    """
    exchange energy
    """
    exchangeCorrelation: Optional[ScalarSchema87] = Field(None, title="scalar schema")
    """
    exchange and correlation energy per particle
    """
    ewald: Optional[ScalarSchema88] = Field(None, title="scalar schema")
    """
    summation of interaction energies at long length scales due to coloumbic interactions
    """
    alphaZ: Optional[ScalarSchema89] = Field(None, title="scalar schema")
    """
    divergent electrostatic ion interaction in compensating electron gas
    """
    atomicEnergy: Optional[ScalarSchema90] = Field(None, title="scalar schema")
    """
    kinetic energy of wavefunctions in the atomic limit
    """
    eigenvalues: Optional[ScalarSchema91] = Field(None, title="scalar schema")
    """
    sum of one electron energies of kinetic, electrostatic, and exchange correlation
    """
    PAWDoubleCounting2: Optional[ScalarSchema92] = Field(None, title="scalar schema")
    """
    double counting correction 2
    """
    PAWDoubleCounting3: Optional[ScalarSchema93] = Field(None, title="scalar schema")
    """
    double counting correction 3
    """
    hartreeFock: Optional[ScalarSchema94] = Field(None, title="scalar schema")
    """
    hartree-fock contribution
    """
    name: Optional[Name701] = None
    units: Optional[Units] = None
