from setuptools import setup, find_packages

# Common dependencies
common_dependencies = [
    "aiohttp",
    "anthropic==0.37.1",
    "autobyteus-llm-client==1.1.2",
    "beautifulsoup4>=4.12.2",
    "boto3",
    "botocore",
    "brui-core==1.0.9",
    "certifi==2025.4.26",
    "google-api-python-client",
    "google-generativeai",
    "Jinja2",
    "mcp[cli]==1.9.1",
    "mistral_common==1.6.3",
    "mistralai",
    "mistralai==1.5.2",
    'numpy==2.2.5',
    "ollama",
    "openai",
    "requests",
    "rich",
    "textual",
    "tiktoken==0.7.0",
]

setup(
    name="autobyteus",
    version="1.1.5",
    packages=find_packages(exclude=["tests", "tests.*"]),
    include_package_data=True,
    install_requires=[
        *common_dependencies,
    ],
    extras_require={
        "dev": [
            "coverage",
            "flake8",
            "numpy",
            "pre-commit",
            "black",
            "isort",
            "gitpython==3.1.31",
            "auto-gpt-plugin-template",
            "mkdocs",
            "pytest",
            "asynctest",
            "pytest-asyncio",
            "pytest-benchmark",
            "pytest-cov",
            "pytest-integration",
            "pytest-mock",
            "vcrpy",
            "pytest-vcr",
            "load_dotenv",
        ],
    },
    python_requires=">=3.8",
    author="Ryan Zheng",
    author_email="ryan.zheng.work@gmail.com",
    description="Multi-Agent framework",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/AutoByteus/autobyteus",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    package_data={
        "autobyteus": ["py.typed"],
    },
)
