from os import environ

import pytz

LINS_HEALTH_CHECK_BASE_URL = environ.get('LINS_HEALTH_CHECK_BASE_URL')

LINS_HEALTH_CHECKS_BASE_API_URL = f'{LINS_HEALTH_CHECK_BASE_URL}/api/v1'

LINS_HEALTH_CHECKS_CHANNELS_URL = f'{LINS_HEALTH_CHECKS_BASE_API_URL}/channels/'

LINS_HEALTH_CHECKS_BADGES_URL = f'{LINS_HEALTH_CHECKS_BASE_API_URL}/badges/'

LINS_HEALTH_CHECKS_CHECKS_URL = f'{LINS_HEALTH_CHECKS_BASE_API_URL}/checks/'

LINS_HEALTH_CHECKS_PING_URL = f'{LINS_HEALTH_CHECK_BASE_URL}/ping/'

HEALTH_CHECKS_REQUEST_TIMEOUT = float(environ.get('HEALTH_CHECKS_REQUEST_TIMEOUT', '10'))

HEALTH_CHECKS_RETRYS = int(environ.get('HEALTH_CHECKS_RETRYS', '0'))

TIMEZONE = pytz.timezone(environ.get('TIMEZONE', 'America/Sao_Paulo'))

SHOW_HEALTH_CHECKS_LOGS = str(environ.get('SHOW_HEALTH_CHECKS_LOGS', 'true')).lower() == 'true'

HEALTH_CHECKS_API_KEY = environ.get('HEALTH_CHECKS_API_KEY')

NO_RESPONSE = 444
