# coding: utf-8

"""
    Eazyrent core API

    EazyRent Core API ====================  Description -------------  The EazyRent API is a powerful tool, designed to automate and streamline the tenant application process for professionals in the real estate and insurance sectors.  Our API leverages advanced technologies like Optical Character Recognition (OCR) and Machine Learning to collect, analyze, and verify tenant application documents.  The API helps clients detect fraudulent submissions and assess the reliability of potential tenants, ensuring a secure and efficient tenant selection process.  Target Audience ----------------   * **Real Estate Agencies and Social Housing Providers:** Professionals who need a reliable solution to evaluate tenant applications quickly and accurately.   * **Rent Guarantee Insurers:** Companies seeking to verify the credibility of tenant applications and assess eligibility for rent payment guarantees.   Purpose --------  The purpose of the EazyRent API is to enable seamless interaction with our tenant application system. It allows clients to integrate our automated document collection, analysis, and verification capabilities directly into their own workflows. By using our API, businesses can streamline operations, reduce fraud risk, and make well-informed decisions in the tenant selection process.   How to use this API ---------------------  To start using the EazyRent API, please refer to our comprehensive online documentation, which includes detailed information on API endpoints, authentication, and integration examples. You can access the documentation [here](https://docs.eazyrent.fr). This resource will guide you through the steps needed to integrate our API into your existing systems and maximize its capabilities.  

    The version of the OpenAPI document: 2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from eazyrent.core.v2.models.open_banking_user_info import OpenBankingUserInfo


class TestOpenBankingUserInfo(unittest.TestCase):
    """OpenBankingUserInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenBankingUserInfo:
        """Test OpenBankingUserInfo
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `OpenBankingUserInfo`
        """
        model = OpenBankingUserInfo()
        if include_optional:
            return OpenBankingUserInfo(
                finances = core.v2.models.finance.Finance(
                    income = core.v2.models.finance_income.FinanceIncome(
                        table = [
                            core.v2.models.income_record.IncomeRecord(
                                paying_institution = core.v2.models.paying_institution.PayingInstitution(
                                    registration_status = '', 
                                    business_sector_code = '', 
                                    registration_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    legal_business_name = '', 
                                    site = core.v2.models.paying_institution_site.PayingInstitutionSite(
                                        registration_number = '', ), 
                                    legal_form = '', 
                                    registration_number = '', 
                                    address = core.v2.models.address.Address(
                                        formatted = '', 
                                        country = 'FR', ), ), 
                                segment = '', 
                                net_amount = null, 
                                start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                type = core.v2.models.income_type.IncomeType(
                                    raw = '', 
                                    normalized = '', ), )
                            ], ), 
                    credit_scoring = core.v2.models.credit_scoring.CreditScoring(
                        score = 56, ), ),
                financials = core.v2.models.financials.Financials(
                    accounts = [
                        core.v2.models.bank_account.BankAccount(
                            iban = '', 
                            account_holder = core.v2.models.bank_account_holder.BankAccountHolder(
                                name = '', ), )
                        ], ),
                name = '',
                birthdate = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return OpenBankingUserInfo(
                finances = core.v2.models.finance.Finance(
                    income = core.v2.models.finance_income.FinanceIncome(
                        table = [
                            core.v2.models.income_record.IncomeRecord(
                                paying_institution = core.v2.models.paying_institution.PayingInstitution(
                                    registration_status = '', 
                                    business_sector_code = '', 
                                    registration_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    legal_business_name = '', 
                                    site = core.v2.models.paying_institution_site.PayingInstitutionSite(
                                        registration_number = '', ), 
                                    legal_form = '', 
                                    registration_number = '', 
                                    address = core.v2.models.address.Address(
                                        formatted = '', 
                                        country = 'FR', ), ), 
                                segment = '', 
                                net_amount = null, 
                                start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                type = core.v2.models.income_type.IncomeType(
                                    raw = '', 
                                    normalized = '', ), )
                            ], ), 
                    credit_scoring = core.v2.models.credit_scoring.CreditScoring(
                        score = 56, ), ),
                financials = core.v2.models.financials.Financials(
                    accounts = [
                        core.v2.models.bank_account.BankAccount(
                            iban = '', 
                            account_holder = core.v2.models.bank_account_holder.BankAccountHolder(
                                name = '', ), )
                        ], ),
                name = '',
                birthdate = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testOpenBankingUserInfo(self):
        """Test OpenBankingUserInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
