LOG_MESSAGES = {
    "token_expired": "Token has expired.",
    "invalid_token": "Invalid token.",
    "error_checking_limit": "Error checking limit: {}",
    "secret": "eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ybE9lZDBvWmVreUN0WjVDZDdYSGFvRTlWY1ciLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwczovL2Zyb250ZW5kLTM2NDYyMjc5NjQ1Lm1lLWNlbnRyYWwyLnJ1bi5hcHAiLCJleHAiOjE3MzIxODQ0MzgsImZ2YSI6Wy0xLC0xXSwiaWF0IjoxNzMyMTg0Mzc4LCJpc3MiOiJodHRwczovL2ZvbmQtc2hlcGhlcmQtNjEuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzMyMTg0MzY4LCJzaWQiOiJzZXNzXzJvdEVCbWFpc05ScnBaZ1hQMFdTVnJURWQ0VyIsInN1YiI6InVzZXJfMmxrTFBRbFI4N3lBUjUxVE9jUnU0dkFCOXllIn0.DAU1_IGKBTEFBZ8NWsOgJKB5hJMyJpqeG5BtQ_0zXbAaMgwswsxitsUpwYEQjYaCjPQq0uSU9O1m7-ukXmTuDVilZdOOKOKXsrBAa-n4ht_F8M4qC9mBbEyl6WEZEIDYLe2fmCDVSdS7_KqfwouDIXOGqKpBb6UZOcNgqOwmGCJEeGzjgkn8hxE7UxljOvIEmcfTjrTzWCzafEu_hTGyxKFGg_gVgqrBnfSZF_0d8xjSHLvcwO9p5iBtlHYA2kqJl_sSLEIiDqgSJT65JlIemzNHjJWVxNtC3qOEsJfImPBV3A1XQrpaQvXf-Dv23vrQMLxTfyBoSjM2qndJtT70Rw",
}
