"""Base storage module defining the storage interface."""

from typing import Any, Iterable, Mapping, Optional

from anymodel.mapper import Mapper
from anymodel.types.mappings import ResultMapping


class Storage:
    """Abstract base class for storage backends.

    All storage implementations must inherit from this class and implement
    the required methods for CRUD operations and schema management.
    """

    def add_table(self, mapper: Mapper): ...
    def migrate(self, **kwargs): ...
    def find_one(self, tablename: str, criteria: dict) -> Optional[ResultMapping]: ...
    def find_many(self, tablename: str, criteria: dict, *, limit=None, offset=None) -> Iterable[ResultMapping]: ...
    def insert(self, tablename: str, values: dict) -> ResultMapping: ...
    def update(self, tablename: str, identity: Mapping[str, Any], values: dict) -> None: ...
    def delete(self, tablename, identity: dict): ...
