from pathlib import Path

from _typeshed import Incomplete

class Greeter:
    word_file_path: Incomplete
    world_file: Incomplete
    language: Incomplete
    def __init__(self, word_file_path: Path) -> None: ...
    def greeting(self) -> str: ...
    def sign_off(self) -> str: ...
    def english_sign_off(self) -> str: ...
