# coding: utf-8

"""
    CyborgDB Service

    REST API for CyborgDB: The Confidential Vector Database

    The version of the OpenAPI document: 0.9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cyborgdb.openapi_client.models.index_operation_request import IndexOperationRequest

class TestIndexOperationRequest(unittest.TestCase):
    """IndexOperationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IndexOperationRequest:
        """Test IndexOperationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IndexOperationRequest`
        """
        model = IndexOperationRequest()
        if include_optional:
            return IndexOperationRequest(
                index_key = '',
                index_name = ''
            )
        else:
            return IndexOperationRequest(
                index_key = '',
                index_name = '',
        )
        """

    def testIndexOperationRequest(self):
        """Test IndexOperationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
