# generated by datamodel-codegen:
#   filename:  properties_directory/structural/magnetic_moments.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Name(Enum):
    magnetic_moments = "magnetic_moments"


class AtomicVectorSchema(BaseModel):
    value: List[float] = Field(..., max_length=3, min_length=3, title="vector 3d schema")
    """
    value of this entry
    """
    id: int
    """
    integer id of this entry
    """


class Units(Enum):
    uB = "uB"


class MagneticMoments(BaseModel):
    name: Optional[Name] = None
    values: Optional[List[AtomicVectorSchema]] = Field(None, title="atomic vectors schema")
    units: Optional[Units] = None
