from ..tensor import Tensor

def add(a: Tensor, b: Tensor) -> Tensor: ...
def sub(a: Tensor, b: Tensor) -> Tensor: ...
def mul(a: Tensor, b: Tensor) -> Tensor: ...
def div(a: Tensor, b: Tensor) -> Tensor: ...