"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .configgroup import ConfigGroup, ConfigGroupTypedDict
from cribl_control_plane.types import BaseModel
from cribl_control_plane.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateGroupsByIDRequestTypedDict(TypedDict):
    id_param: str
    r"""Group ID"""
    config_group: ConfigGroupTypedDict
    r"""ConfigGroup object"""


class UpdateGroupsByIDRequest(BaseModel):
    id_param: Annotated[
        str,
        pydantic.Field(alias="id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Group ID"""

    config_group: Annotated[
        ConfigGroup,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""ConfigGroup object"""


class UpdateGroupsByIDResponseTypedDict(TypedDict):
    r"""a list of ConfigGroup objects"""

    count: NotRequired[int]
    r"""number of items present in the items array"""
    items: NotRequired[List[ConfigGroupTypedDict]]


class UpdateGroupsByIDResponse(BaseModel):
    r"""a list of ConfigGroup objects"""

    count: Optional[int] = None
    r"""number of items present in the items array"""

    items: Optional[List[ConfigGroup]] = None
